# Arquivo de manifeto da aplicação de check list com banco de dados posgre e front nodeJS tudo separado em micro-serviços container e usamos um conatiner Docker onde está aplicação.
--- 
apiVersion: v1
kind: Service  
metadata:
  name: postgre
  namespace: dev 
  labels:
    app: postgre 
spec: 
  ports:
    - port: 5432  
  selector:
    app: postgre
  clusterIP: None

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-app
  resources:
    requests:
      storage: 1Gi

--- 
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: postgre 
  namespace: dev  
  labels:
    app: postgre
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - image: postgres:14.3   
          name: postgre
          env:
          - name: POSTGRES_PASSWORD
            value: P@ssWord25485
          ports:
          - containerPort: 5432
            name: postgre  

          volumeMounts:
          - name: postgre-volume
            mountPath: /var/lib/postgre  
          env: 
          - name: POSTGRES_USER
            value: "kubenews"  
          - name: POSTGRES_DB
            value: "kubenews" 

      volumes:
      - name: postgre-volume
        persistentVolumeClaim:
          claimName: postgre-pvc    
--- 





apiVersion: apps/v1
kind: Deployment  
metadata:
  name:  kubenews 
  namespace: dev  
spec:
  replicas: 2 #qtde de pod 
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels: 
        app: kubenews
    spec:
      containers:
      - name: kubenews  # nome dos pod
        image: nandocloud/kube-new:v2  #imagem no  dockerhub essa imagem está na 8 versão de teste 
        env:        
        - name: DB_DATABASE  #acesso ao dados da aplicação na criação do banco postgre
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "P@ssWord25485"
        - name: DB_HOST
          value: "postgre"
--- 

     



apiVersion: v1
kind: Service  
metadata:
  name: kube-news 
  namespace: dev 
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080 
    nodePort: 30017  
  type: NodePort

